aid: adyen:adyen-configuration-api
name: Adyen Configuration API
description: >-
  The Configuration API enables you to create a platform where you can onboard
  your users as account holders and create balance accounts, cards, and business
  accounts.
url: https://raw.githubusercontent.com/api-search/payments/main/_apis/adyen/apis.md
