name: APIs.io
description: The first API search engine.
image: https://kinlane-productions2.s3.amazonaws.com/apis-json/apis-json-logo.jpg
url: https://apis.io

node: website

keywords:

  - APIs
  - Search
  - Discovery

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

categories_path : /categories.html
tags_path : /tags.html

github_org: api-search
github_repo: website

search_local: false
search_url: https://search-api.apis.io/search/apis

paginate:           25
paginate_path:      "/blog/:num/"