name: APIs.io
description: Search and discover APIs by what you want to accomplish. Find API providers, individual APIs, capabilities, and schemas across the APIs.io network.
image: https://apis.io/assets/branding/apisio-social-card.png
url: https://apis.io

node: website
nav_active: search

keywords:
  - APIs
  - Search
  - Discovery
  - API Directory
  - API Catalog
  - REST APIs
  - APIs.json
  - Capabilities

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "scripts", "_shared"]
include: [".well-known"]

# Site-wide alert banner
alert:
    enabled:        false
    type:           danger
    message:        'This Search is in an Alpha Stage -- <a href="https://github.com/api-search/explore/issues">Submit An Issue</a>!'

categories_path : /categories.html
tags_path : /tags.html

github_org: api-search
github_repo: network

paginate:           25
paginate_path:      "/blog/:num/"
