aid: >-
  intercom-intercom-openapi-an-openapi-description-for-intercom-s-rest-api:intercom-intercom-openapi-an-openapi-description-for-intercom-s-rest-api
name: 'intercom/Intercom-OpenAPI: An OpenAPI description for Intercom''s REST API'
description: >-
  This repository contains OpenAPI descriptions for Intercom's REST API ~
  https://github.com/intercom/Intercom-OpenAPI
url: >-
  https://example.com/apis/intercomintercom-openapi-an-openapi-description-for-intercoms-rest-api.yml
