aid: >-
  getlago-lago-openapi-open-api-specification-for-lago-project:getlago-lago-openapi-open-api-specification-for-lago-project
name: 'getlago/lago-openapi: Open API specification for Lago project'
description: >-
  Open API specification for Lago project ~
  https://github.com/getlago/lago-openapi?tab=readme-ov-file
url: >-
  https://example.com/apis/getlagolago-openapi-open-api-specification-for-lago-project.yml
