aid: microsoft-azure-one-:applicationinsightsclient
name: ApplicationInsightsClient
description: >-
  This document describes the protocol for client requests and responses to the
  data collection endpoint.
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure/apis.md
