aid: microsoft-azure-one-:applicationinsightsmanagementclient
name: ApplicationInsightsManagementClient
description: Azure Application Insights private workbook type.
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure/apis.md
