aid: microsoft-azure-one-:azure-cdn-webapplicationfirewallmanagement
name: Azure CDN WebApplicationFirewallManagement
description: APIs to manage web application firewall rules for Azure CDN
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure/apis.md
