aid: stripe:stripe-application-secrets-api
name: Stripe Application Secrets API
description: >-
  Secret Store is an API that allows Stripe Apps developers to securely persist
  secrets for use by UI Extensions and app backends.
url: >-
  https://raw.githubusercontent.com/api-search/payments/main/_apis/stripe/apis.md
