aid: swagger-ui:swagger-ui
name: Swagger UI
description: >-
  The Crossref REST API is one of a variety of tools and APIs that allow anybody
  to search and reuse our members' metadata in sophisticated ways.If you read
  nothing else, please at least look at the API TIPs document and the
  "Etiquette" section of this document. It will save you (and us) much
  heartburn. ~ https://api.staging.crossref.org/swagger-ui/index.html
url: https://example.com/apis/swagger-ui-tlbCNBUK.yml
