aid: microsoft-azure:appserviceenvironments-api-client
name: AppServiceEnvironments API Client
description: null
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
