aid: microsoft-azure:data-sensitivity-settings
name: Data Sensitivity Settings
description: API spec for Microsoft.Security Data Sensitivity Settings
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
