aid: microsoft-azure:guest-diagnostic-settings-association-api
name: Guest Diagnostic Settings Association API
description: >-
  API to Add/Remove/List Guest Diagnostics Settings Association for Azure
  Resources
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
