aid: microsoft-azure:managedapplicationclient
name: ManagedApplicationClient
description: ARM managed applications (appliances)
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
