aid: microsoft-azure:microsoft-security
name: Microsoft.Security
description: REST APIs for Defender for DevOps
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
