aid: microsoft-azure:networkmanageractiveconfiguration
name: NetworkManagerActiveConfiguration
description: >-
  The Microsoft Azure Network Manager Active Configuration API provides a
  RESTful set of web services that interact with Microsoft Azure Network Manager
  service to list all active configuration by network manager.
url: >-
  https://raw.githubusercontent.com/api-search/cloud/main/_apis/microsoft-azure-2/apis.md
