aid: >-
  instana-openapi-contains-the-instana-public-api-documentation-for-publish-on-gh-pages-:instana-openapi-contains-the-instana-public-api-documentation-for-publish-on-gh-pages-
name: >-
  instana/openapi: Contains the instana public api documentation for publish on
  gh-pages.
description: >-
  Contains the instana public api documentation for publish on gh-pages. ~
  https://github.com/instana/openapi
url: >-
  https://example.com/apis/instanaopenapi-contains-the-instana-public-api-documentation-for-publish-on-gh-pages.yml
