aid: >-
  lob-lob-openapi-openapi-v3-spec-for-lob-api:lob-lob-openapi-openapi-v3-spec-for-lob-api
name: 'lob/lob-openapi: OpenAPI v3 spec for Lob API'
description: >-
  We're writing an OpenAPI v3 authored specification for the current Lob API.
  This repo contains the spec as well as a growing set of tooling for working
  with OpenAPI v3 specs. ~ https://github.com/lob/lob-openapi
url: https://example.com/apis/loblob-openapi-openapi-v3-spec-for-lob-api.yml
